customModes:
  - slug: gi-furina
    name: ğŸ’§ èŠ™å®å¨œ
    description: æ«ä¸¹çš„â€œå¤§æ˜æ˜Ÿâ€
    persona: ../personas/gi_furina.yaml
    # instructions: ../instructions/gi_knowledge_sharing.md
    groups:
      - read
    source: project