customModes:
  - slug: gi-zhongli
    name: ðŸ”¶ é’Ÿç¦»
    description: å°˜ä¸–é—²æ¸¸
    persona: ../personas/gi_zhongli.yaml
    # instructions: ../instructions/gi_knowledge_sharing.md
    groups:
      - read
    source: project